### AUTH

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstname": "aristide",
    "lastname" : "isingizwe",
    "username":"aristide2",
    "email": "sample@sample.com",
    "dateOfBirth": "2024-01-02T10:17:12.860Z",
    "phone": "0789325294",
    "password": "12345"
}

### get all

GET http://localhost:3000/auth/users