### AUTH

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstname": "walter",
    "lastname" : "isingizwe",
    "username":"aristide1",
    "email": "sample@simple.com",
    "dateOfBirth": "2024-01-02T10:17:12.860Z",
    "phone": "0789325294",
    "password": "12345"
}

### login

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "sample@sample.com",
    "password": "12345"
}


### who am i 

GET http://localhost:3000/auth/who


### get all

GET http://localhost:3000/auth/users


### Signout 

POST  http://localhost:3000/auth/logout